"""
Django settings for nwg_performance project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import environ
env = environ.Env()
environ.Env.read_env("variable.env")


UAT_CONFIG = {
    'username': env('UAT_USERNAME'),
    'password': env('UAT_PASSWORD'),
    'otp_secret': env('UAT_OTP_SECRET'),
    'token_path': env('UAT_TOKEN_PATH'),
}
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dy4%ijt+_e^1$lb#4_=ov!q8hzxzt10ctik+tlz((@-!6nybm='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['ios.nwg_performance.ir', 'www.ios.nwg_performance.ir', '10.133.49.102']

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ios_input',
    'sla',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nwg_performance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nwg_performance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': '4rfvBGT_',#os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST', 'postgres'),
        'PORT': '5432',
    }
}


# CLICKHOUSE_PASSWORD = 'yVqT337zeYJU3BUjNWk9etMTLV5HwbCm'
# CLICKHOUSE_CL2_PASSWORD = 'f4v5omKYwBbQFC'
# CLICKHOUSE_TASK_PASSWORD = 'vmUP9iMoom9DJM3U7MtqsiTfgZ27wxdf'
# CLICKHOUSE = dict(
#     HOST="10.225.32.101",
#     PORT=9000,
#     DATABASE="ios",
#     USERNAME="ios",
#     PASSWORD=CLICKHOUSE_TASK_PASSWORD,
#     TASK_USERNAME="ios",
#     TASK_PASSWORD=CLICKHOUSE_TASK_PASSWORD,
#     # CL2_HOST="10.224.235.38",
#     # CL2_USERNAME="ios",
#     # CL2_PASSWORD=passwd.CLICKHOUSE_CL2_PASSWORD,
#     # CL2_PORT=8702,
#     CL2_HOST="10.224.235.35",
#     CL2_USERNAME="ios",
#     CL2_PASSWORD=CLICKHOUSE_CL2_PASSWORD,
#     CL2_PORT=9001,
#     CM_TABLE="dist_cm",
#     LOG_TABLE="dist_django_log_staging",
#     CL4_HOST="10.225.32.101",
#     CL4_USERNAME="ios",
#     CL4_PORT=9000,
#     CL4_PASSWORD=CLICKHOUSE_PASSWORD
# )
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
