version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: nwg_performance
      POSTGRES_USER: nwg_performance
      POSTGRES_PASSWORD: 4rfvBGT_
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"  # Host:5435 → Container:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nwg_performance -d nwg_performance"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/app
    ports:
      - "8005:8005"  # Host:8005 → Container:8005
    environment:
      DATABASE_URL: postgres://nwg_performance:4rfvBGT_@postgres:5432/nwg_performance
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: