version: '3.8'

services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin_password_123
      CLICKHOUSE_DB: nwg
      ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - nwg
      - common

  nwg_postgres:
    container_name: nwg_postgres
    image: postgres:13
    environment:
      POSTGRES_DB: nwg_performance
      POSTGRES_USER: nwg_performance
      POSTGRES_PASSWORD: 4rfvBGT_
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - ./nwg_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nwg_performance -d nwg_performance"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nwg
      - common

  nwg-backend:
    container_name: nwg-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8005"
    volumes:
      - .:/app
    ports:
      - "8005:8005"
    environment:
      POSTGRES_DB: nwg_performance
      POSTGRES_USER: nwg_performance
      POSTGRES_PASSWORD: 4rfvBGT_
      POSTGRES_HOST: nwg_postgres
      CLICKHOUSE_URL: http://clickhouse:8123
    depends_on:
      clickhouse:
        condition: service_healthy
      nwg_postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nwg
      - common

volumes:
  nwg_postgres_data:
  clickhouse_data:

networks:
  nwg:
    driver: bridge
  common:
    external: true
    name: nwg-network
